# Change these first
owner: elfsquad # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Elfsquad homepage
    url: https://www.elfsquad.io/
  - name: EMS
    url: https://ems.elfsquad.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://www.elfsquad.io/hubfs/Elfsquad%20-%20Rebrand/Logo/elfsquad-primary-white.svg
  favicon: https://www.elfsquad.io/hubfs/Elfsquad%20-%20Rebrand/Favicon/favicon-32x32.png
  name: Elfsquad Status
  introTitle: "**Elfsquad** System Status"
  introMessage: This page provides real-time status information for Elfsquad services. Check back here for updates on any service disruptions.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Elfsquad
      href: https://www.elfsquad.io
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: |
    :root {
      --color-background: #00221f;
      --color-background-secondary: #003330;
    }
    body {
      background-color: #00221f;
    }
    nav {
      background-color: #00221f;
    }

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
