# Change these first
owner: elfsquad # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Elfsquad homepage
    url: https://www.elfsquad.io/
  - name: EMS
    url: https://ems.elfsquad.io/
  - name: Data API
    url: https://api.elfsquad.io/data/1/health/ready
  - name: Configurator API
    url: https://api.elfsquad.io/configurator/1/health/ready
  - name: Quotation API
    url: https://api.elfsquad.io/quotation/1/health/ready
  - name: Core API
    url: https://api.elfsquad.io/api/2/health/ready
i18n:
  footer: Elfsquad - 2026

status-website:
  baseUrl: /upptime
  logoUrl: https://www.elfsquad.io/hubfs/Elfsquad%20-%20Rebrand/Logo/elfsquad-primary-white.svg
  favicon: https://www.elfsquad.io/hubfs/Elfsquad%20-%20Rebrand/Favicon/favicon-32x32.png
  name: Elfsquad Status
  introTitle: "**Elfsquad** System Status"
  introMessage: This page provides real-time status information for Elfsquad services. Check back here for updates on any service disruptions.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Elfsquad
      href: https://www.elfsquad.io
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600&display=swap');
    :root {
      --color-background: #00221f;
      --color-background-secondary: #003330;
      --color-text: #ffffff;
      --color-text-secondary: #cccccc;
    }
    body {
      background-color: #00221f;
      font-family: 'Instrument Sans', sans-serif;
    }
    nav {
      background-color: #00221f;
    }

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
